name: Terraform Auto Deploy

on:
  push: {}

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false -var="db_password=${{ secrets.DB_PASSWORD }}" -var="hr_password=${{ secrets.HR_PASSWORD }}"

      - name: Terraform Apply (zonder ECS/ELB)
        run: |
          terraform apply -auto-approve \
            -target=aws_ecr_repository.php_app \
            -target=aws_db_instance.hr_database \
            -target=null_resource.create_tables \
            -target=aws_vpc.hr \
            -target=aws_subnet.subnet_db1 \
            -target=aws_subnet.subnet_db2 \
            -target=aws_subnet.subnet_web \
            -target=aws_subnet.subnet_lb1 \
            -target=aws_subnet.subnet_lb2 \
            -target=aws_security_group.sg_database \
            -target=aws_security_group.sg_webserver \
            -target=aws_security_group.sg_loadbalancer \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="hr_password=${{ secrets.HR_PASSWORD }}"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: php-app
          IMAGE_TAG: latest
        run: |
          cd website
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Terraform Apply (rest - ECS en ELB)
        run: terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}" -var="hr_password=${{ secrets.HR_PASSWORD }}"